module.exports = Object.freeze({
  // HOST: "http://localhost:3000/",
  HOST: "https://copybin4u.web.app/",
  SERVERHOST: "https://copybinback.herokuapp.com",

  WEBSITE: "Copy>Bin",
  PUBLICCODES: "Public>Codes",
  PASTE: "Generate>Pastes",
  ENCRYPTDECRYPTHEADING: "Encrypt/Decrypt",
  // LINEARALGEBRA: "Linear Algebra",
  HOME: "Sections",
  ABOUT: "About",
  UPLOADTEXT: "Upload file",
  GENERATELINK: "Generate>Link",
  // NUMBERTHEORY: "Number>Theory",
  MOREPRODUCTS: "More>Utilities",
  DEFAULTTHEME: "monokai",
  DEFAULTMODE: "javascript",

  THEMES: [
    "monokai",
    "github",
    "tomorrow",
    "kuroir",
    "twilight",
    "xcode",
    "textmate",
    "solarized_dark",
    "solarized_light",
    "terminal",
  ],
  MODES: [
    "javascript",
    "java",
    "python",
    "xml",
    "ruby",
    "sass",
    "markdown",
    "mysql",
    "json",
    "html",
    "handlebars",
    "golang",
    "csharp",
    "elixir",
    "typescript",
    "css",
  ],

  TERTIARY: "#fff",
  PRIMARY: "#ead9ff",
  SECONDARY: "#5c4e6e",
  MONOKAI: "#5c4e6e",
  HEADING: "#fff",
  MONOKAILIGHT: "#a3a3a3",
  PRODUCTS: [
    {
      name: "Encrypt/Decrypt file",
      key: HOST + "encrypt_decrypt",
    },
    {
      name: "Code>bin (Website for computer science students)",
      key: "https://codebin4u.web.app/",
    },
  ],
});
